# Site settings
title: Romantic Coder Blog
url: "https://zhangxiang2014.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Beijing
description: >
  这里有片麦田，我会在这里守望.

# Your information
email: 805198265@qq.com
author: 诗意的猿
avatar: "http://upload.jianshu.io/users/upload_avatars/1420306/d083fd3309f2.jpg?imageMogr2/auto-orient/strip|imageView2/1/w/240/h/240"
profile: 这里有片麦田，我会在这里守望.
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
